version: '2'
services:
  db:
    image: postgres
    container_name: app-Postgre
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: app-RubyOnRails
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
